import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Jack',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jay',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      //_id: '1',
      name: 'Denim Jacket',
      slug: 'Hip-Hop-Denim-Jackets',
      category: 'Cassual',
      image: '/images/p1.jpg',
      price: 180,
      countInStock: 10,
      brand: 'AllSaints',
      rating: 4.5,
      numReviews: 10,
      description: 'Men Denim Jacket Streetwear Hip Hop Hooded Jean Jacket',
    },
    {
      //_id: '2',
      name: 'Nike Airforce 1',
      slug: 'Nike-Air-Shadow',
      category: 'Cassual Shoes',
      image: '/images/p2.jpg',
      price: 200,
      countInStock: 10,
      brand: 'Nike',
      rating: 5,
      numReviews: 12,
      description: 'Unisex Nike Air Shoes',
    },
    {
      //_id: '3',
      name: 'HRX Socks',
      slug: 'Sports-Cassual-Socks',
      category: 'Sports',
      image: '/images/p3.jpg',
      price: 10,
      countInStock: 15,
      brand: 'HRX',
      rating: 4,
      numReviews: 9,
      description: 'Sports & Gym Socks',
    },
    {
      //_id: '4',
      name: 'Winter Shoes',
      slug: 'men-s-winter-home-cotton-shoes',
      category: 'Cassual',
      image: '/images/p4.jpg',
      price: 100,
      countInStock: 10,
      brand: 'Unbranded',
      rating: 4.5,
      numReviews: 10,
      description: 'New Mens Winter Home Cotton Shoes Cute Black',
    },
  ],
};
export default data;
